<div class="master-password-login">
    <div class="page-title">
        <h1><?php echo $this->__('Login to customer account from admin') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div>
        <div class="content">
        	<a href="<?php echo $this->getUrl('adminhtml')?>"><?php echo $this->__('Go back to admin') ?></a>
    	</div>
	</div>
    <!--<form action="<?php #echo $this->getLoginPostUrl() ?>" method="post" id="master-password-login-form">
    	<div>
        	<div class="content">
            	<ul class="form-list">
                	<li>
                    	<label for="email" class="required"><em>*</em><?php #echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                        	<input type="text" name="login[username]" value="<?php #echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php #echo $this->__('Email Address') ?>" />
                        </div>
                    </li>
                    <li>
                    	<label for="pass" class="required"><em>*</em><?php #echo $this->__('Password') ?></label>
                        <div class="input-box">
                        	<input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php #echo $this->__('Password') ?>" />
                        </div>
                    </li>
                </ul>
                <p class="required"><?php #echo $this->__('* Required Fields') ?></p>
            </div>
    	</div>
    	<div class="buttons-set">
            <button type="submit" class="button" title="<?php #echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php #echo $this->__('Login') ?></span></span></button>
        </div>
    </form>-->
    <script type="text/javascript">
    //<![CDATA[
        //var dataForm = new VarienForm('master-password-login-form', true);
    //]]>
    </script>
</div>